language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

install: 
  - pip install --upgrade pip
  - cd app
  - pip install .
  - pip install -e '.[dev]'

services:
- docker

env:
  matrix:
  - GH_VERSION=1.0.4 TAGS=1.0.4,latest

script:
- cd ${TRAVIS_BUILD_DIR}
- make test
- make

deploy:
  provider: script
  script: bash ${TRAVIS_BUILD_DIR}/release.sh
  on:
    branch: master
