sudo: true
dist: python:3.8

jobs:
  include:
    - stage: test python app
      script:
      - cd app
      - pip install -e '.[dev]'
      - pytest
    - stage: build docker image
      script:
      - make
    # - stage: publish
    #   script: bash ${TRAVIS_BUILD_DIR}/release.sh
